
# Simple neural network

**Problem description:**

Implement a 3 layer, feed-forward neural network architecture, with the goal to differentiate between 20x20 images showing handwritten digits from 0 to 9.

Neural network architecture:
- input layer: 20x20=400 units
- hidden layer: 25 units
- output layer: 10 unit

The weights of the network are already trained and given to you.

In [1]:
import os
setup_script = os.path.join(os.environ['ENV_JUPYTER_SETUPS_DIR'], 'setup_sci_env_basic.py')
%run $setup_script

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
import scipy.io
from scipy import optimize
import matplotlib.colors as mcolors

In [3]:
data = scipy.io.loadmat('ex3data1.mat')
weights = scipy.io.loadmat('ex3weights.mat')

In [4]:
features = data['X']
labels = data['y'][:,0]
X = np.insert(data['X'], 0, 1, axis=1)
y = data['y'][:,0]

In [5]:
X.shape

(5000, 401)

In [6]:
theta1 = weights['Theta1']
theta2 = weights['Theta2']

In [7]:
theta1.shape

(25, 401)

In [8]:
theta2.shape

(10, 26)

In [9]:
def ReLu(z):
    if z < 0:
        return 0
    if z >= 0:
        return z

In [10]:
def sigmoid(z):
    return 1.0/(1.0+np.exp(-z))

In [11]:
def activation_function(weights, X):
    z = weights.dot(X)
    fval = sigmoid(z)
    #fval = ReLu(z)
    return fval

In [12]:
X.T.shape

(401, 5000)

In [13]:
a2 = activation_function(theta1, X.T)
a2 = np.insert(a2, 0, 1, axis=0)

In [14]:
a2.shape

(26, 5000)

In [15]:
a3 = activation_function(theta2, a2)

In [16]:
a3.shape

(10, 5000)

In [17]:
y_pred = np.argmax(a3, axis=0)+1

In [18]:
y_pred.shape

(5000,)

In [19]:
y_pred

array([10, 10, 10, ...,  9,  9,  9])

In [20]:
data['y']

array([[10],
       [10],
       [10],
       ..., 
       [ 9],
       [ 9],
       [ 9]], dtype=uint8)

In [21]:
y

array([10, 10, 10, ...,  9,  9,  9], dtype=uint8)

In [22]:
y_pred == y

array([ True,  True,  True, ...,  True,  True,  True], dtype=bool)

**Accuracy:**

In [23]:
np.mean(y_pred == y)

0.97519999999999996